# This is a basic workflow to help you get started with Actions

name: Delete Branch

# Controls when the workflow will run
on: delete

jobs:
  #This workflow contains a single job called "build"
  deleteCloudFormation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Copy File From S3
        run: aws cloudformation delete-stack --stack-name ${{ github.event.ref }}
